theme: jekyll-theme-minimal
title: Mulloy Morrow
description: A personal static website. 
logo: favicon.png

author: Mulloy Morrow
shortcut icon: favicon.ico

# Google Analytics
google_analytics: G-VLHNVPE3GR

minima:
  social_links:
    twitter: thismulloy
    github:  mulloymorrow
    instagram: mulloymorrow
    linkedin: mulloymorrow
    telegram: mulloy
